project:
  type: website
  output-dir: docs

website:
  title: "Benefit Risk Decision Enhanced Visualizations"
  search:
    location: navbar
    type: overlay
  page-navigation: true
  navbar:
    pinned: true
    collapse: false
    background: primary
    search: true
    right:
        - href: index.qmd
          text: "Home"
        - text: "Visualizations"
          menu:
            - text: "Demographics (Pyramid Chart)"
              href: R/pyramid_chart.qmd
            - text: "Disease History (Line Chart)"
              href: R/line_chart.qmd
            - text: "Comorbidities (Grouped Bar Chart)"
              href: R/grouped_barchart.qmd
            - text: "Value Tree"
              href: R/Value_Tree.qmd
            - text: "Dot-Forest Plot"
              href: R/dot_forest_plot.qmd
            - text: "Trade-off Plot"
              href: R/tradeoff_plot.qmd
            - text: "Correlogram"
              href: R/correlogram.qmd
            - text: "Scatterplot"
              href: R/scatterplot_function.qmd
            - text: "Composite Outcome (Stacked Bar Chart)"
              href: R/stacked_barchart.qmd
            - text: "Cumulative Excess Plot"
              href: R/cumulative_excess_functions.qmd
        - text: "News"
          href: news_1.qmd
        - text: "Contributions"
          href: CONTRIBUTING.qmd
        - text: "About Us"
          href: aboutus.qmd

  sidebar:
    - id: logo
      style: docked
      collapse-level: 1
      logo: images/brlogo.png
      border: false


format:
  html:
    css: styles.css
    header-includes:
      - "<style>
         /* Full-width sticky header */
         .sticky-header {
           position: fixed;
           top: 0;
           left: 0;
           width: 100%;
           background-color: #333;
           color: #fff;
           text-align: center;
           padding: 0px 0;
           font-size: 0em;
           font-weight: bold;
           z-index: 1000;
           margin: 0;
           box-shadow: 0 0px 0px rgba(0, 0, 0, 0.2);
         }
         body {
           margin-top: 0px; /* Adjust based on header height */
         }
        </style>
        <div class=\"sticky-header\">
          Benefit Risk Charts
        </div>"

    theme: flatly
    toc: true
    toc-location: right

site-url: "https://br-visualization.github.io/br-visualization/"
repo-url: "https://github.com/BR-Visualization/br-visualization"
repo-actions: [edit, issue]

editor: visual
