---
title: "News"
---

# Progress is the attraction that moves humanity {style="color: darkgreen"}

\~Marcus Garvey

<div style="color: black">

------------------------------------------------------------------------

If you would like to stay updated with details of our package development, please visit our [News](NEWS.md) page.

------------------------------------------------------------------------

</div>

### May, 2025 {style="color: black"}

#### **Goals Achieved:** {style="color: black"}

-   First drafts created for the enhanced cumulative excess plot

-   First drafts created for the enhanced scatter plot

-   Continued discussion of proposed manuscript and revision of enhancements

#### **Action Items:** {style="color: black"}

-   Continue to enhance static chart visualizations

-   Discuss updates with the large team, and gather preliminary feedback

------------------------------------------------------------------------

### April, 2025 {style="color: black"}

#### **Goals Achieved:** {style="color: black"}

-   First drafts created for the enhanced dot-forest plot

-   Finalized first draft of static charts site

-   Discussed strategy of enhancing plots, progression of the manuscript, and future community engagement

#### **Action Items:** {style="color: black"}

-   Continue revising and enhancing plots from static charts site

-   Plan large team meeting to continue discussions

------------------------------------------------------------------------

### March, 2025 {style="color: black"}

#### **Goals Achieved:** {style="color: black"}

-   Create new repository for proposed manuscript (brpubVJCE)

-   Wonderful Wednesday presentation and visualization discussion

-   Create new repository for static charts site (brdevs)

-   Large team meeting to discuss contribution guidelines, proposed visualizations, and next steps

#### **Action Items:** {style="color: black"}

-   Begin working on enhancements for proposed manuscript

-   Continue brpubVJCE and brdevs set-up

------------------------------------------------------------------------

### February, 2025 {style="color: black"}

#### **Goals Achieved:** {style="color: black"}

-   Installation Issues resolved utilizing Codespaces with brcharts(1)

-   Proposed goals and objectives for brcharts

-   Issue template implementation

#### **Action Items:** {style="color: black"}

-   Revising goals and objectives

-   Renaming strategy to advance static charts work

------------------------------------------------------------------------

### January, 2025 {style="color: black"}

#### **Goals Achieved:** {style="color: black"}

-   Discuss Benefit-Risk working groups

-   Propose ideas for building static charts repo

#### **Action Items:** {style="color: black"}

-   Draft aims and objectives for brcharts

-   Investigate installation issues for brcharts(1)

-   Investigate template for Chart GitHub issue
